# 4 jobs, Job 4 depends on 1,2,3. On Push, each job will print current Date, Job 1 - Ubuntu-latest, Job 2 - Windows-latest, Job 3 - MacOs-latest, last job free to use
name: exercise2
on: push
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - run: date
  job2:
    name: Job 2
    runs-on: windows-latest
    steps:
      - run: Get-Date
  job3:
    name: Job 3
    runs-on: macos-latest
    steps:
      - run: date
  job4:
    name: Job4 Depends on 1,2,3
    runs-on: macos-latest
    needs: [job1, job2, job3]
    steps:
      - run: date
