name: Excercise 3 - Artifacts
on: [push]
env:
  ARTIFACT_NAME: newArtifact
jobs:
  artifact: 
    name: Create and Upload Artifact
    runs-on: macos-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: $newArtifact # or ${{ env.ARTIFACT_NAME }} -- Only restriction is to not use it with this YAML notation if env var was declared on same step
        
